name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -Dmaven.test.skip=true
        
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: target.jar
          path: target/trade-plateform-0.0.1-SNAPSHOT.jar
